# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_kotlin_version=1.13.13+kotlin.2.4.10

# Mod Properties
mod_version=1.0.2
maven_group=me.e_chan.mod.simplecoordinatehud
archives_base_name=simplecoordinatehud

# Dependencies
# fabric_version=0.97.3+1.20.4
fabric_api_version=0.155.2+26.2
yacl_version=3.9.6+26.2-fabric
modmenu_version=20.0.1
matrix_color_api_version=v1.0.7
